name: Deploy to Coolify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Coolify Deployment
        run: |
          curl --request GET \
            --url 'http://169.58.26.173:8000/api/v1/deploy?uuid=wvjplbj1fq5jnlg8cied2rvh&force=false' \
            --header 'Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}'
